### ISSUE TITLE
Client [MRT-Power-Meter-7691794] connection closed: timeout

### ISSUE THREAD

**Issue by w00dst0ck** [mrebbert/FerrarisPowerMeter#3]
Source | Date | Level | Message
-- | -- | -- | --
mqtt.0 | 2021-10-26 11:44:42.131 | info | Client [MRT-Power-Meter-7691794] connected with secret 1635241482130_4615
mqtt.0 | 2021-10-26 11:44:26.718 | info | Client [MRT-Power-Meter-7691794] connection closed: timeout

I see reconnects in the logs very often.
Does anyone else have these messages in their logs as well?

**Comment by mrebbert** [comment]
I no longer use the sensor, but I do not remember these log messages. Does the problem still exist?

**Comment by w00dst0ck** [comment]
@mrebbert In the meantime, my meter has been exchanged for a digital one.
